# Pipeline variables
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -Dmaven.repo.local=.m2/repository --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_CLI_OPTS_VERSION: "help:evaluate -Dexpression=project.version -q -DforceStdout"
  GIT_SUBMODULE_STRATEGY: recursive
  NODE_OPTIONS: "--max-old-space-size=8192"
  

# Cache policy - Share target folders between jobs - Note that key is related to a commit and is purged automatically after pipeline execution
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $CI_PROJECT_DIR/.m2/repository/**/*
    - $CI_PROJECT_DIR/**/target/**/*

include:
  - project: 'boost/template-ci/pipelines/common'
    file: 'docker/docker-template.yml'
  - project: 'bots/trivy-script'
    file: 'trivy-template-job.yml' 

default:
  image: maven:3.9.6-eclipse-temurin-17
  
  before_script:
    - apt update && apt install -y gettext-base build-essential
    - envsubst '${MVN_GROUP} ${MVN_RELEASE} ${MVN_SNAPSHOTS}' < pom.xml > pom.subst && mv -f pom.subst pom.xml

# Stages definition
stages:
  - build
  - test
  - pre_docker
  - docker
  - deploy

# Build job with maven plugin execution policies define in parent pom
pluievolutionapi:build:
  script:
    - PROJET_VERSION=$(sh ./mvnw $MAVEN_CLI_OPTS_VERSION)
    - echo "PROJET_VERSION=$PROJET_VERSION" >> build.env
    - echo $PROJET_VERSION
    - sh ./mvnw $MAVEN_CLI_OPTS -U package -Pprod
  stage: build
  except:
    refs:
      - master
      - open/master
  artifacts:
    reports:
      dotenv:
        - build.env
    paths:
      - $CI_PROJECT_DIR/georchestra-plui-evolution-api/target/georchestra-plui-evolution-api-*.jar
      - $CI_PROJECT_DIR/georchestra-plui-evolution-api/target/georchestra-plui-evolution-api-*.war
      
pluievolutionapi:build:master:
  script:
    - PROJET_VERSION=$(sh ./mvnw $MAVEN_CLI_OPTS_VERSION)
    - echo "PROJET_VERSION=$PROJET_VERSION" >> build.env
    - echo $PROJET_VERSION
    - sh ./mvnw $MAVEN_CLI_OPTS -U package -DskipTests -Pprod 
  stage: build
  only:
    refs:
      - master
      - open/master   
  artifacts:
    reports:
      dotenv:
        - build.env
    paths:
      - $CI_PROJECT_DIR/georchestra-plui-evolution-api/target/georchestra-plui-evolution-api-*.jar
      - $CI_PROJECT_DIR/georchestra-plui-evolution-api/target/georchestra-plui-evolution-api-*.war

# Sonar code quality analysis - note a full test coverage report through a jacoco.exec merged file in base project folder
pluievolutionapi:sonar:
  stage: test
  dependencies:
    - pluievolutionapi:build
  except:
    refs:
      - master
      - open/master
  allow_failure: true
  script:
    - >
      sh ./mvnw $MAVEN_CLI_OPTS -U compile sonar:sonar
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME

# On master, do not use branch parameter
pluievolutionapi:sonar:master:
  stage: test
  dependencies:
    - pluievolutionapi:build
  only:
    refs:
      - open/master
  allow_failure: true
  script:
    - >
      sh ./mvnw $MAVEN_CLI_OPTS -U compile sonar:sonar
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID

# Copie des artifacts dans les répertoires des images dockers
pluievolutionapi:pre_docker:
  stage: pre_docker
  only:
    refs:
      - master
      - open/master
      - open/develop
      - /^release.*/
  script:
    - PROJET_VERSION=$(sh ./mvnw $MAVEN_CLI_OPTS_VERSION)
    - echo "PROJET_VERSION=$PROJET_VERSION" >> build.env
    - echo $PROJET_VERSION  
    - ls $CI_PROJECT_DIR/georchestra-plui-evolution-api/target/
    - cp -f $CI_PROJECT_DIR/georchestra-plui-evolution-api/target/georchestra-plui-evolution-api-$PROJET_VERSION.war /var/lib/jetty/webapps/plui-evolution.war
  artifacts:
    paths:
      - '$CI_PROJECT_DIR/docker/**/**.jar'

pluievolutionapi:docker:build:
  extends: ['.docker:build']
  needs:
    - pluievolutionapi:pre_docker
  dependencies:
    - pluievolutionapi:pre_docker
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /.*develop/ || $CI_COMMIT_BRANCH =~ /.*master/ || $CI_COMMIT_BRANCH =~ /^release.*/'
  timeout: 2h

.pluievolutionapi:deploy:
  stage: deploy
  tags: 
   - iaas
  image: glregistry.boost.open.global/boost/docker/mvn-node-jdk11-ansible:latest
  dependencies:
    - pluievolutionapi:build
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ansible_private_key" | base64 -d)     
  script:
    - PROJET_VERSION=$(sh ./mvnw $MAVEN_CLI_OPTS_VERSION)
    - echo "PROJET_VERSION=$PROJET_VERSION" >> build.env
    - echo $PROJET_VERSION
    - cp -f $CI_PROJECT_DIR/georchestra-plui-evolution-api/target/georchestra-plui-evolution-api-$PROJET_VERSION.war $CI_PROJECT_DIR/ansible/dockerize/files/georchestra-plui-evolution-api.war
    - cp -f $CI_PROJECT_DIR/georchestra-plui-evolution-api/target/georchestra-plui-evolution-api-$PROJET_VERSION.jar $CI_PROJECT_DIR/ansible/dockerize/files/georchestra-plui-evolution-api.jar
    - cd $CI_PROJECT_DIR/ansible
    #- chmod og-rw key/id_rsa
    - cp plui-evolution_dev_var.yml $HOME/plui-evolution_var.yml
    - ansible-playbook plui-evolution-docker.yml -v -i "${TARGET_ENV}," -u root --ssh-common-args=-oStrictHostKeyChecking=no

pluievolutionapi:deploy:
  extends: .pluievolutionapi:deploy
  only:
    refs:
      - open/develop
  variables: 
    TARGET_ENV: REN1VML0096
    
pluievolutionapi:deploy:master:
  extends: .pluievolutionapi:deploy
  only:
    refs:
      - open/master
  variables: 
    TARGET_ENV: REN1VML0095
    
pluievolutionapi:trivyscan:front: 
  extends: 
    - .trivy-scan
  stage: docker
  variables:
    TRIVY_DOCKER_SCAN: glregistry.boost.open.global/rennes-metropole/plui-evolution/plui-evolution/plui-evolution:open-develop
  only:
    refs:
      - open/develop      
 