apiVersion: v1
kind: Secret
metadata:
  name: pluievolution-secret-dev
  labels:
    app.kubernetes.io/instance: pluievolution-secret-dev
    app.kubernetes.io/name: pluievolution-secret-dev
    environnement: dev
type: Opaque
data:
  database.pluievolution.password: cGx1aWV2b2x1dGlvbg==